# Generated by Django 2.1.5 on 2020-01-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_businesscashbonus_booking'),
        ('points', '0002_auto_20200103_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpoint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
        migrations.AddField(
            model_name='rewardpoint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
        migrations.AddField(
            model_name='virtualpoint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
    ]
