# Generated by Django 2.1.5 on 2019-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankCountry', models.CharField(blank=True, max_length=200, null=True)),
                ('bankName', models.CharField(blank=True, max_length=200, null=True)),
                ('swiftCode', models.IntegerField(blank=True, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('accountName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Detail',
            },
        ),
    ]
