# Generated by Django 2.1.5 on 2019-10-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='invoiceTo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
