# Generated by Django 2.1.5 on 2019-10-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_merge_20191002_1638'),
        ('account', '0004_bankdetail_invoiceto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotels'),
        ),
    ]
