# Generated by Django 2.1.5 on 2019-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bankdetail_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='swiftCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
