# Generated by Django 2.1.5 on 2019-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
