# Generated by Django 2.1.5 on 2020-01-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_faq_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bankCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
    ]
