# Generated by Django 2.1.5 on 2020-02-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200113_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='bankCountry',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='BankDetail',
        ),
    ]
