# Generated by Django 2.1.5 on 2020-04-03 03:39

import account.owner_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=account.owner_profile.models.photo_path),
        ),
    ]
