# Generated by Django 2.1.5 on 2020-04-02 06:07

import account.owner_profile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0084_auto_20200327_1021'),
        ('account', '0012_auto_20200203_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='document',
            field=models.FileField(blank=True, default='default.png', upload_to=account.owner_profile.models.doc_path),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='document_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='owner_or_manager',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=500, upload_to=account.owner_profile.models.photo_path),
        ),
    ]
