# Generated by Django 2.1.5 on 2020-04-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200402_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner_or_manager',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
