# Generated by Django 2.1.5 on 2020-04-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200403_0924'),
        ('account', '0014_auto_20200402_0821'),
    ]

    operations = [
    ]
