# Generated by Django 2.1.5 on 2020-04-05 11:57

import account.owner_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_20200404_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=500, upload_to=account.owner_profile.models.photo_path),
        ),
    ]
