# Generated by Django 2.1.5 on 2019-09-20 05:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('contactno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.CharField(max_length=80)),
                ('is_primary', models.CharField(default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('contact', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('gender', models.CharField(max_length=8, null=True)),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
