"""
Django settings for travel project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
try:
    import pymysql

    pymysql.install_as_MySQLdb()
except:
    pass

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jz44$b3ru2oji%tss&c^avm!c-^t9zjm4dq^0^xl)8cue$s8qh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    'ads.gorkha.tech',
    '178.128.27.245',
    '127.0.0.1',
    'localhost'
]

# Application definition

INSTALLED_APPS = [
    'users',
    'hotel',
    'account',
    'booking',
    'points',
    'group',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_seed',
    'django.contrib.admin',
    'django.contrib.auth',
    'session_security',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cloud Messaging
    'fcm_django',
    'requests'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'travel.mymiddleware.MyMiddleware',
]
ROOT_URLCONF = 'travel.urls'

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

url = BASE_DIR
TIME_INPUT_FORMATS = ('%H:%M',)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'travel/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hotel.context_processors.hotelDashboard',
                'hotel.context_processors.approvalcount',
                'hotel.context_processors.invcount',
                # 'hotel.context_processors.rentalcount',
                # 'hotel.context_processors.rentalinvcount',
                'booking.contextprocessors.membershipUpgradesCount',
                'booking.contextprocessors.PartnershipUpgradesCount',
                'booking.contextprocessors.moduleCount',
                # 'travel_tour.context_processors.travelDashboard',
                # 'hotel.context_processors.restaurantcount',
                # 'hotel.context_processors.restaurantinvcount',
                'hotel.context_processors.hotelBookingCount',
                'hotel.context_processors.hotel_side_navigation',
                'hotel.context_processors.property_list',

                # 'hotel.context_processors.hotel_name'

            ],
        },
    },
]

WSGI_APPLICATION = 'travel.wsgi.application'
USE_TZ = False
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_bigsafarhotel',
        'USER': 'c4c',
        'PASSWORD': 'paradise',
        'HOST': 'localhost',
        'PORT': '',
        'CHARSET': 'utf8',
        'COLLATION': 'utf8_general_ci',
        'OPTIONS': {
            # "init_command": "SET foreign_key_checks = 0;",
            # 'sql_mode': 'traditional',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
# PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR,'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'hotel/media')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Custom django auth settings


AUTH_USER_MODEL = 'account.User'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_REDIRECT_URL = 'PropertyDetail'
LOGOUT_REDIRECT_URL = 'login'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_HOST_USER = 'info@ktmvoyage.com'
EMAIL_HOST_PASSWORD = '@Kathmandu11'
EMAIL_PORT = 587
FINANCE_MEDIA_BASE_SHIVAJI = 'http://128.199.22.231:8006/'
# FINANCE_MEDIA_BASE_SHIVAJI = 'http://127.0.0.1:8006/'

DEFAULT_FROM_EMAIL = 'KTM VOYAGE <info@ktmvoyage.com>'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES':
    # (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),

}

FCM_DJANGO_SETTINGS = {
    # "FCM_SERVER_KEY": "AAAA3NA05hg:APA91bEMIshdoF3qqIJEFIh4AuMwzdXZ6-9Xu3L-hjnDVXmo83YtlM8E-gh_XOGCo6gsEWEwnNNTpJunv2mP0wqDnUToytrgot4e9-ZUibsqX6Gu7wVtftKM5yCy_3RTKjYEPvkGXLX3"
    "FCM_SERVER_KEY": "AAAAP975rcQ:APA91bHiryAAYnfpz-vgt-5wjld5Qh6m4cTnMysMDQC00ThpNoUOtrNEonO1rR3q6YlOpvJKGOjgFyDqCn7BfOTspD0ch5uIuoWC86SIerqTPOcWGVeK7TjlPkZe1c7tOdD-PlcPrAGT"
}

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SECURITY_INSECURE = True
SESSION_SECURITY_EXPIRE_AFTER = 30 * 60
SESSION_SECURITY_WARN_AFTER = 20 * 60

FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")
