# Generated by Django 2.1.5 on 2019-10-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_passwordreset'),
        ('booking', '0001_initial'),
        ('points', '0001_initial'),
        ('hotel', '0004_merge_20191002_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeandreferred',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memtype', to='points.Membership_plan'),
        ),
        migrations.AddField(
            model_name='refereeandreferred',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnertype', to='booking.BusinessPartners'),
        ),
        migrations.AddField(
            model_name='refereeandreferred',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='booking.Customer', unique=True),
        ),
        migrations.AddField(
            model_name='pointslog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointsfor', to='booking.Customer'),
        ),
        migrations.AddField(
            model_name='modulebooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.BookingTable'),
        ),
        migrations.AddField(
            model_name='modulebooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='booking.Customer'),
        ),
        migrations.AddField(
            model_name='hotelbookinglog',
            name='module_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_booking', to='booking.ModuleBooking'),
        ),
        migrations.AddField(
            model_name='hotelbookinglog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='account.StaffProfile'),
        ),
        migrations.AddField(
            model_name='guestdocdetail',
            name='guest_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.GuestDetail'),
        ),
        migrations.AddField(
            model_name='guestdocdetail',
            name='issuing_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingTable'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.City'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Customer'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='memplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='points.Membership_plan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='partnerplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='booking.BusinessPartners'),
        ),
        migrations.AddField(
            model_name='businesscashbonus',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
        migrations.AddField(
            model_name='businesscashbonus',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingTable'),
        ),
        migrations.AddField(
            model_name='businesscashbonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Customer'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to='booking.Customer'),
        ),
    ]
