# Generated by Django 2.1.5 on 2019-11-06 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191002_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='memplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membershipofcustomer', to='points.Membership_plan'),
        ),
    ]
