# Generated by Django 2.1.5 on 2019-11-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20191106_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereeandreferred',
            name='membership',
        ),
    ]
