# Generated by Django 2.1.5 on 2019-11-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_refereeandreferred_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetail',
            name='state',
        ),
        migrations.AlterField(
            model_name='guestdetail',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetail',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='guestdocdetail',
            name='issuing_country',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
