# Generated by Django 2.1.5 on 2019-12-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20191114_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulebooking',
            name='booking',
        ),
    ]
