# Generated by Django 2.1.5 on 2019-12-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_modulebooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.ModuleBooking'),
        ),
    ]
