# Generated by Django 2.1.5 on 2019-12-17 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingtable_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebooking',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
