# Generated by Django 2.1.5 on 2019-12-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_modulebooking_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetail',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
    ]
