# Generated by Django 2.1.5 on 2020-01-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20191225_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='booking',
        ),
        migrations.AddField(
            model_name='modulebooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_booking', to='booking.BookingTable'),
        ),
        migrations.AlterField(
            model_name='guestdetail',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_booking', to='booking.BookingTable'),
        ),
    ]
