# Generated by Django 2.1.5 on 2020-01-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20200103_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscashbonus',
            name='booking',
        ),
    ]
