# Generated by Django 2.1.5 on 2020-01-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_businesscashbonus_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscashbonus',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ModuleBooking'),
        ),
    ]
