# Generated by Django 2.1.5 on 2020-01-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_businesscashbonus_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulebooking',
            name='customer',
        ),
    ]
