# Generated by Django 2.1.5 on 2020-01-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_modulebooking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbookinglog',
            name='module_booking',
        ),
        migrations.AddField(
            model_name='hotelbookinglog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_table', to='booking.BookingTable'),
        ),
    ]
