# Generated by Django 2.1.5 on 2020-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_bookingtable_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='pin',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
