# Generated by Django 2.1.5 on 2020-03-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20200303_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulebooking',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
