# Generated by Django 2.1.5 on 2020-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20200304_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
