# Generated by Django 2.1.5 on 2020-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20200304_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
