# Generated by Django 2.1.5 on 2020-03-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20200304_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.GuestDetail'),
        ),
        migrations.AddField(
            model_name='guestdetail',
            name='parent_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
