# Generated by Django 2.1.5 on 2020-03-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20200305_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetail',
            name='booking',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_guest', to='booking.GuestDetail'),
        ),
    ]
