# Generated by Django 2.1.5 on 2020-03-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20200305_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guestdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='guestdetail',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='guestdetail',
            name='gender',
        ),
    ]
