# Generated by Django 2.1.5 on 2019-09-20 05:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Bed Type',
            },
        ),
        migrations.CreateModel(
            name='Cancellation_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Cancellation Policy',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='HotelAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Hotel Amenities',
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_of_adult', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('no_of_child', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('no_of_room', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pay_mode', models.CharField(max_length=10)),
                ('pay_status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Hotel Bookings',
            },
        ),
        migrations.CreateModel(
            name='HotelFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Hotel Amenities',
            },
        ),
        migrations.CreateModel(
            name='HotelFacilitiesMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFacilitiesMiddleNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hotel & Room Gallery',
            },
        ),
        migrations.CreateModel(
            name='HotelInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('child_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('extra_bed', models.BooleanField(blank=True, default=False)),
                ('no_of_extra_bed', models.IntegerField(blank=True, null=True)),
                ('ppextrabed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adult_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('no_of_rooms', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('priceforadult', models.TextField(blank=True)),
                ('agerangeforinfant', models.CharField(blank=True, max_length=30, null=True)),
                ('discountforinfant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agerangeforchild', models.CharField(blank=True, max_length=30, null=True)),
                ('discountforchild', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Hotel Inventory',
            },
        ),
        migrations.CreateModel(
            name='hotelinventory_amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelamenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotel.HotelAmenities')),
                ('hotelinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_hotel', to='hotel.HotelInventory')),
            ],
        ),
        migrations.CreateModel(
            name='hotelinventory_roomfeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.HotelInventory')),
            ],
        ),
        migrations.CreateModel(
            name='hotelinventory_roomtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelinventory', to='hotel.HotelInventory')),
            ],
        ),
        migrations.CreateModel(
            name='HotelLanguageMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HotelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'verbose_name_plural': 'Hotel Log',
            },
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('address', models.CharField(max_length=80, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_hotel', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hotel Owners',
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('inventory_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('review', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Review and Rating',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hotel Room Features',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hotel Room Type',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_room', models.IntegerField(default=0)),
                ('number_of_staff', models.IntegerField(default=0)),
                ('wordsbyowner', models.TextField(blank=True, default='words by owner')),
                ('description', models.TextField(blank=True)),
                ('star_rating', models.CharField(blank=True, max_length=40)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('rateforforeign', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ratefornepali', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rateforsaarc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldhotelid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('number_of_room', models.IntegerField(default=0)),
                ('number_of_staff', models.IntegerField(default=0)),
                ('wordsbyowner', models.TextField(blank=True, default='words by owner')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('facilities', models.ManyToManyField(related_name='facilitiessNew', through='hotel.HotelFacilitiesMiddleNew', to='hotel.HotelFacilities')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OwnerProfile')),
            ],
            options={
                'verbose_name_plural': 'HotelsNew',
            },
        ),
        migrations.CreateModel(
            name='HotelStaff',
            fields=[
                ('name', models.CharField(max_length=80, null=True)),
                ('contact', models.BigIntegerField(null=True, unique=True)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('address', models.CharField(max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Hotel Staffs',
            },
        ),
        migrations.CreateModel(
            name='Inventory_Bed_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_type', to='hotel.BedType')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_bed_type', to='hotel.HotelInventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory Bed Types',
            },
        ),
        migrations.CreateModel(
            name='InventoryGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('hotel_inventory_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory')),
            ],
            options={
                'verbose_name_plural': 'Hotel & Room Gallery',
            },
        ),
        migrations.CreateModel(
            name='InventoryOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hotel_inventory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_offer', to='hotel.HotelInventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory Offers',
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Landmarks',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('banner_image', models.ImageField(default='default.png', upload_to='')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('module', models.CharField(blank=True, max_length=80, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.OwnerProfile')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, max_length=60, null=True)),
                ('end_date', models.DateField(blank=True, max_length=60, null=True)),
                ('nameofdepositor', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contact1', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Spotlight',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='HotelAddress',
            fields=[
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='hotel.Hotels')),
                ('address', models.CharField(max_length=80, null=True)),
                ('contact1', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact2', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.AddField(
            model_name='spotlight',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight', to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='inventoryoffers',
            name='offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Offers'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelOwner'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='facilities',
            field=models.ManyToManyField(related_name='facilitiess', through='hotel.HotelFacilitiesMiddle', to='hotel.HotelFacilities'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='languages',
            field=models.ManyToManyField(related_name='languages', through='hotel.HotelLanguageMiddle', to='account.Language'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OwnerProfile'),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotellanguagemiddle',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_language', to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='hotellanguagemiddle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelfacility', to='account.Language'),
        ),
        migrations.AddField(
            model_name='hotelinventory_roomtype',
            name='hotelroomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype', to='hotel.HotelRoomType'),
        ),
        migrations.AddField(
            model_name='hotelinventory_roomfeatures',
            name='hotelroomfeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomfeature', to='hotel.HotelRoomFeature'),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='amenities',
            field=models.ManyToManyField(through='hotel.hotelinventory_amenities', to='hotel.HotelAmenities'),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='roomfeatures',
            field=models.ManyToManyField(through='hotel.hotelinventory_roomfeatures', to='hotel.HotelRoomFeature'),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='roomtype',
            field=models.ManyToManyField(through='hotel.hotelinventory_roomtype', to='hotel.HotelRoomType'),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelgallery',
            name='hotel_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddlenew',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelnew', to='hotel.HotelsNew'),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddlenew',
            name='hotelsfacilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelfacilitynew', to='hotel.HotelFacilities'),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel.Hotels'),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='hotelsfacilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelfacility', to='hotel.HotelFacilities'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotelinventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.State'),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='hotel.HotelInventory'),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.City'),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country'),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='landmarks',
            field=models.ManyToManyField(related_name='hotellandmarks', to='hotel.Landmark'),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.State'),
        ),
    ]
