# Generated by Django 2.1.5 on 2019-10-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotels_estd_date'),
        ('hotel', '0003_auto_20191002_1202'),
    ]

    operations = [
    ]
