# Generated by Django 2.1.5 on 2019-10-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20191003_0656'),
        ('hotel', '0004_merge_20191002_1638'),
    ]

    operations = [
    ]
