# Generated by Django 2.1.5 on 2019-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20191018_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
