# Generated by Django 2.1.5 on 2019-11-13 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20191018_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory',
            name='infant_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
