# Generated by Django 2.1.5 on 2019-11-27 05:54

from django.db import migrations, models
import hotel.gallery.models
import hotel.inventorygallery.models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelinventory_infant_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=hotel.gallery.models.photo_path),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(default='default.png', upload_to=hotel.models.photo_path),
        ),
        migrations.AlterField(
            model_name='inventorygallery',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=hotel.inventorygallery.models.photo_path),
        ),
    ]
