# Generated by Django 2.1.5 on 2019-11-27 07:01

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20191127_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(default='default.png', max_length=500, upload_to=hotel.models.photo_path),
        ),
    ]
