# Generated by Django 2.1.5 on 2019-11-27 07:17

from django.db import migrations, models
import hotel.inventorygallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20191127_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygallery',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=500, upload_to=hotel.inventorygallery.models.photo_path),
        ),
    ]
