# Generated by Django 2.1.5 on 2019-11-27 07:54

from django.db import migrations, models
import hotel.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20191127_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='image',
            field=models.ImageField(default='default.png', max_length=500, upload_to=hotel.inventory.models.photo_path),
        ),
    ]
