# Generated by Django 2.1.5 on 2019-11-27 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20191127_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventorygallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='You cannot enter number here.', regex='^[a-zA-Z]*$')]),
        ),
    ]
