# Generated by Django 2.1.5 on 2019-12-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_hotelinventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='adult_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
