# Generated by Django 2.1.5 on 2019-12-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_auto_20191201_1030'),
        ('hotel', '0018_auto_20191201_1211'),
    ]

    operations = [
    ]
