# Generated by Django 2.1.5 on 2019-12-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Customer'),
        ),
    ]
