# Generated by Django 2.1.5 on 2019-12-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_auto_20191225_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=80, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=False)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotels')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory Updates',
            },
        ),
    ]
