# Generated by Django 2.1.5 on 2020-01-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_auto_20200108_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='ppextrabed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
