# Generated by Django 2.1.5 on 2020-01-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_auto_20200116_0535'),
        ('hotel', '0025_auto_20200112_1348'),
    ]

    operations = [
    ]
