# Generated by Django 2.1.5 on 2020-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_merge_20200117_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='inventory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
