# Generated by Django 2.1.5 on 2020-02-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_auto_20200131_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=200, null=True)),
                ('swiftCode', models.CharField(blank=True, max_length=200, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('accountName', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceTo', models.CharField(blank=True, max_length=200, null=True)),
                ('bankCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotels')),
            ],
            options={
                'verbose_name_plural': 'Bank Detail',
            },
        ),
    ]
