# Generated by Django 2.1.5 on 2020-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_auto_20200206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='no_show',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
