# Generated by Django 2.1.5 on 2020-02-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_auto_20200206_0627'),
        ('hotel', '0031_cancellation_policy_no_show'),
    ]

    operations = [
    ]
