# Generated by Django 2.1.5 on 2020-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_auto_20200207_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
