# Generated by Django 2.1.5 on 2020-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_addonservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservices',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
