# Generated by Django 2.1.5 on 2020-02-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_b2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory_amenities',
            name='hotelamenities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotel.HotelAmenities'),
        ),
        migrations.AlterField(
            model_name='hotelinventory_amenities',
            name='hotelinventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_hotel', to='hotel.HotelInventory'),
        ),
    ]
