# Generated by Django 2.1.5 on 2020-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_merge_20200210_1520'),
        ('hotel', '0033_b2b'),
        ('hotel', '0034_addonservices_status'),
    ]

    operations = [
    ]
