# Generated by Django 2.1.5 on 2020-02-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_auto_20200212_1058'),
        ('hotel', '0035_merge_20200213_1703'),
    ]

    operations = [
    ]
