# Generated by Django 2.1.5 on 2020-02-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_addonservices_status'),
        ('hotel', '0035_auto_20200212_1058'),
    ]

    operations = [
    ]
