# Generated by Django 2.1.5 on 2020-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_merge_20200225_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory',
            name='bb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='ep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
