# Generated by Django 2.1.5 on 2020-02-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_auto_20200225_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinventory',
            name='bb',
        ),
        migrations.RemoveField(
            model_name='hotelinventory',
            name='ep',
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='bedandbreakfast_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='european_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
