# Generated by Django 2.1.5 on 2020-02-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_childsupplementpolicy'),
        ('hotel', '0038_auto_20200226_1122'),
    ]

    operations = [
    ]
