# Generated by Django 2.1.5 on 2020-02-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_auto_20200226_1122'),
        ('hotel', '0037_childsupplementpolicy'),
        ('hotel', '0036_merge_20200225_0750'),
    ]

    operations = [
    ]
