# Generated by Django 2.1.5 on 2020-02-28 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_merge_20200228_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromage', models.IntegerField(blank=True, null=True)),
                ('toage', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('freeorpaid', models.BooleanField(default=False)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('invid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_policy_inv', to='hotel.HotelInventory')),
            ],
            options={
                'verbose_name_plural': 'Children Policy',
            },
        ),
    ]
