# Generated by Django 2.1.5 on 2020-03-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0040_children_policy'),
        ('hotel', '0039_merge_20200228_1337'),
    ]

    operations = [
    ]
