# Generated by Django 2.1.5 on 2020-03-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_merge_20200301_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
