# Generated by Django 2.1.5 on 2020-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_merge_20200301_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenities',
            name='chargeable',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
