# Generated by Django 2.1.5 on 2020-03-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_merge_20200301_0544'),
        ('hotel', '0041_merge_20200301_1114'),
    ]

    operations = [
    ]
