# Generated by Django 2.1.5 on 2020-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_auto_20200302_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='modification_allow',
            field=models.BooleanField(default=False),
        ),
    ]
