# Generated by Django 2.1.5 on 2020-03-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_remove_hotelinventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory_roomfeatures',
            name='hotelinventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.HotelInventory'),
        ),
        migrations.AlterField(
            model_name='hotelinventory_roomfeatures',
            name='hotelroomfeature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomfeature', to='hotel.HotelRoomFeature'),
        ),
    ]
