# Generated by Django 2.1.5 on 2020-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_auto_20200302_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellation_policy',
            old_name='charge',
            new_name='charge_cancel',
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='card_detail_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='charge_modification',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='cvc_required',
            field=models.BooleanField(default=False),
        ),
    ]
