# Generated by Django 2.1.5 on 2020-03-04 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0045_merge_20200302_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_inventory', models.BigIntegerField(blank=True, null=True)),
                ('altered_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Price Altered Table',
            },
        ),
        migrations.AlterField(
            model_name='hotelinventory',
            name='bedandbreakfast_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinventory',
            name='european_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
