# Generated by Django 2.1.5 on 2020-03-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_cancellation_policy_cancel_allow'),
        ('hotel', '0041_merge_20200301_0544'),
        ('hotel', '0044_auto_20200302_1003'),
    ]

    operations = [
    ]
