# Generated by Django 2.1.5 on 2020-03-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_cancellation_policy_cancel_allow'),
        ('hotel', '0044_auto_20200302_1003'),
        ('hotel', '0042_merge_20200302_1053'),
    ]

    operations = [
    ]
