# Generated by Django 2.1.5 on 2020-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_auto_20200304_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='bedandbreakfast_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelinventory',
            name='european_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
