# Generated by Django 2.1.5 on 2020-03-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_merge_20200303_1303'),
        ('hotel', '0042_merge_20200302_1053'),
    ]

    operations = [
    ]
