# Generated by Django 2.1.5 on 2020-03-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_auto_20200304_1252'),
        ('hotel', '0048_merge_20200305_1510'),
    ]

    operations = [
    ]
