# Generated by Django 2.1.5 on 2020-03-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_merge_20200306_0509'),
        ('hotel', '0047_merge_20200308_1021'),
    ]

    operations = [
    ]
