# Generated by Django 2.1.5 on 2020-03-08 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_merge_20200306_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('citytax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Country')),
            ],
        ),
    ]
