# Generated by Django 2.1.5 on 2020-03-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_remove_childsupplementpolicy_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsupplementpolicy',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='childSupplement', to='hotel.Hotels'),
            preserve_default=False,
        ),
    ]
