# Generated by Django 2.1.5 on 2020-03-06 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_extrabedpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='cribsPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(blank=True, max_length=200, null=True)),
                ('age_start', models.IntegerField(blank=True, null=True)),
                ('age_end', models.IntegerField(blank=True, null=True)),
                ('cost_status', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cribs', to='hotel.Hotels')),
            ],
            options={
                'verbose_name_plural': 'Cribs Policy',
            },
        ),
    ]
