# Generated by Django 2.1.5 on 2020-03-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0052_cribspolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children_policy',
            name='invid',
        ),
        migrations.DeleteModel(
            name='Children_Policy',
        ),
    ]
