# Generated by Django 2.1.5 on 2020-03-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_specialrequest'),
        ('hotel', '0047_merge_20200308_1021'),
        ('hotel', '0050_charges'),
    ]

    operations = [
    ]
