# Generated by Django 2.1.5 on 2020-03-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_merge_20200308_1104'),
        ('hotel', '0054_specialrequest'),
        ('hotel', '0050_charges'),
    ]

    operations = [
    ]
