# Generated by Django 2.1.5 on 2020-03-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0055_merge_20200308_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='bedandbreakfast_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelinventory',
            name='european_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
