# Generated by Django 2.1.5 on 2020-03-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_auto_20200311_0455'),
        ('hotel', '0055_merge_20200308_1330'),
    ]

    operations = [
    ]
