# Generated by Django 2.1.5 on 2020-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
