# Generated by Django 2.1.5 on 2020-03-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_merge_20200311_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Cancellation_Policy'),
        ),
    ]
