# Generated by Django 2.1.5 on 2020-03-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_cancellation_policy_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='hotelInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory'),
        ),
    ]
