# Generated by Django 2.1.5 on 2020-03-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_cancellation_policy_hotelinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation_policy',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='hotel.Hotels'),
        ),
    ]
