# Generated by Django 2.1.5 on 2020-03-12 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_similarsystems'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInDiffSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_other_sys', to='hotel.HotelInventory')),
                ('meal_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_other_sys', to='hotel.MealPlan')),
                ('other_systems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sys', to='hotel.SimilarSystems')),
            ],
        ),
    ]
