# Generated by Django 2.1.5 on 2020-03-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0060_priceindiffsys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceindiffsys',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_other_sys', to='hotel.HotelInventory'),
        ),
    ]
