# Generated by Django 2.1.5 on 2020-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0060_auto_20200311_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='change_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
