# Generated by Django 2.1.5 on 2020-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0062_auto_20200315_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsupplementpolicy',
            name='change_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
