# Generated by Django 2.1.5 on 2020-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0062_auto_20200312_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='ppextrabed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
