# Generated by Django 2.1.5 on 2020-03-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_childsupplementpolicy_change_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrabedpolicy',
            name='change_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extrabedpolicy',
            name='hotelInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory'),
        ),
        migrations.AddField(
            model_name='extrabedpolicy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.ExtraBedPolicy'),
        ),
    ]
