# Generated by Django 2.1.5 on 2020-03-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0064_auto_20200315_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cribspolicy',
            name='change_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cribspolicy',
            name='hotelInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelInventory'),
        ),
        migrations.AddField(
            model_name='cribspolicy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.cribsPolicy'),
        ),
    ]
