# Generated by Django 2.1.5 on 2020-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0067_auto_20200315_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupdate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
