# Generated by Django 2.1.5 on 2020-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0068_auto_20200315_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
