# Generated by Django 2.1.5 on 2020-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0069_auto_20200315_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation_policy',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='season_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='season_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
