# Generated by Django 2.1.5 on 2020-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0070_auto_20200315_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation_policy',
            name='day',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
