# Generated by Django 2.1.5 on 2020-03-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_auto_20200316_0715'),
        ('hotel', '0071_auto_20200315_2210'),
    ]

    operations = [
    ]
