# Generated by Django 2.1.5 on 2020-03-19 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0072_merge_20200319_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryupdate',
            name='date',
        ),
        migrations.AddField(
            model_name='childsupplementpolicy',
            name='day',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='childsupplementpolicy',
            name='season_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childsupplementpolicy',
            name='season_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryupdate',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
