# Generated by Django 2.1.5 on 2020-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0076_auto_20200319_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrabedpolicy',
            name='day',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extrabedpolicy',
            name='season_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrabedpolicy',
            name='season_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
