# Generated by Django 2.1.5 on 2020-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0077_auto_20200319_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation_policy',
            name='hour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cancellation_policy',
            name='no_show',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cancellation_policy',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
