# Generated by Django 2.1.5 on 2020-03-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0077_auto_20200319_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealterlog',
            name='altered_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
