# Generated by Django 2.1.5 on 2020-03-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0080_pricealterlog_altered_group'),
        ('hotel', '0078_auto_20200322_1244'),
    ]

    operations = [
    ]
