# Generated by Django 2.1.5 on 2020-03-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0081_merge_20200323_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialrequest',
            name='hotel',
        ),
    ]
