# Generated by Django 2.1.5 on 2020-03-27 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0082_remove_specialrequest_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.IntegerField(blank=True, null=True)),
                ('range_end', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprate', to='hotel.Hotels')),
            ],
            options={
                'verbose_name_plural': 'GroupRate',
            },
        ),
    ]
