# Generated by Django 2.1.5 on 2020-04-03 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0084_auto_20200327_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelgallery',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
