# Generated by Django 2.1.5 on 2020-04-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0085_hotelgallery_created_at'),
        ('hotel', '0086_auto_20200403_0926'),
    ]

    operations = [
    ]
