# Generated by Django 2.1.5 on 2020-04-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0087_merge_20200404_1311'),
        ('hotel', '0087_auto_20200405_0727'),
    ]

    operations = [
    ]
