# Generated by Django 2.1.5 on 2020-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0088_merge_20200405_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
