# Generated by Django 2.1.5 on 2020-04-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0092_auto_20200407_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='prop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.PropertyDetail'),
        ),
    ]
