# Generated by Django 2.1.5 on 2020-04-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0093_hotels_prop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='cino',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='estd_date',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='nameonpancard',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='pannumber',
        ),
    ]
