# Generated by Django 2.1.5 on 2020-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0094_auto_20200408_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='freeorpaid',
            field=models.CharField(default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='isrecomended',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelfacilitiesmiddle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
