# Generated by Django 2.1.5 on 2020-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0095_auto_20200408_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfacilities',
            name='category',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
