# Generated by Django 2.1.5 on 2020-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0096_hotelfacilities_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfacilitiesmiddle',
            options={'verbose_name_plural': 'HotelFacilitiesMiddle'},
        ),
        migrations.AddField(
            model_name='bedtype',
            name='roomtype',
            field=models.ManyToManyField(to='hotel.HotelRoomType'),
        ),
    ]
