# Generated by Django 2.1.5 on 2020-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0098_auto_20200410_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory',
            name='room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='room_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
