# Generated by Django 2.1.5 on 2020-04-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0099_auto_20200412_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedtype',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='bedtype',
            name='roomtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelRoomType'),
        ),
    ]
