# Generated by Django 2.1.5 on 2020-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0100_auto_20200412_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedtype',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
