# Generated by Django 2.1.5 on 2020-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0101_bedtype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
