# Generated by Django 2.1.5 on 2020-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0102_auto_20200414_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomfeature',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
