# Generated by Django 2.1.5 on 2020-04-14 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0104_remove_hotelamenities_chargeable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('chargeable', models.BooleanField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Room Facilities',
            },
        ),
    ]
