# Generated by Django 2.1.5 on 2020-04-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0105_roomfacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenities',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
