# Generated by Django 2.1.5 on 2020-04-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0106_hotelamenities_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelinventory_roomfacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelinventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_for_facility', to='hotel.HotelInventory')),
                ('roomfacility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomfacility', to='hotel.RoomFacilities')),
            ],
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='roomfacility',
            field=models.ManyToManyField(through='hotel.hotelinventory_roomfacility', to='hotel.RoomFacilities'),
        ),
    ]
