# Generated by Django 2.1.5 on 2020-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0108_auto_20200415_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory',
            name='room_size_unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
