# Generated by Django 2.1.5 on 2020-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0109_hotelinventory_room_size_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory',
            name='extra_crib',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='hotelinventory',
            name='no_of_extra_crib',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
