# Generated by Django 2.1.5 on 2020-04-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0110_auto_20200416_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinventory',
            name='ppextrabed',
        ),
    ]
