# Generated by Django 2.1.5 on 2020-04-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0111_remove_hotelinventory_ppextrabed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='room_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
