# Generated by Django 2.1.5 on 2020-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0113_hotelinventory_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinventory_roomfacility',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelinventory_roomfacility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
