# Generated by Django 2.1.5 on 2020-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0114_auto_20200419_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinventory',
            name='bedandbreakfast_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinventory',
            name='european_plan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
