# Generated by Django 2.1.5 on 2020-04-22 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0118_paymentpolicies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPaymentPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alternative_address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotels')),
                ('invoice_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.PropertyDetail')),
                ('primary_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelAddress')),
            ],
            options={
                'verbose_name_plural': 'Commission Payment Policies',
            },
        ),
    ]
