# Generated by Django 2.1.5 on 2020-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0119_commissionpaymentpolicies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='credit_card_policy',
            field=models.ManyToManyField(related_name='credit_card_policy', through='hotel.PaymentPolicies', to='hotel.CreditCard'),
        ),
    ]
