# Generated by Django 2.1.5 on 2020-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0120_hotels_credit_card_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='credit_card_policy',
        ),
    ]
