# Generated by Django 2.1.5 on 2020-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0121_remove_hotels_credit_card_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenities',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
