# Generated by Django 2.1.5 on 2020-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0122_hotelamenities_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
