# Generated by Django 2.1.5 on 2020-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0123_auto_20200424_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenities',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
