# Generated by Django 2.1.5 on 2020-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0124_auto_20200424_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='cancel_allow',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='card_detail_required',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='change_status',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='charge_cancel',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='charge_modification',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='cvc_required',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='modification_allow',
        ),
        migrations.RemoveField(
            model_name='cancellation_policy',
            name='parent',
        ),
        migrations.AddField(
            model_name='cancellation_policy',
            name='cancellation_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
