# Generated by Django 2.1.5 on 2020-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0125_auto_20200501_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryupdate',
            old_name='end_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inventoryupdate',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='inventoryupdate',
            name='cancellation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryupdate',
            name='is_booked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
