# Generated by Django 2.1.5 on 2020-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0126_auto_20200510_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygallery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
