# Generated by Django 2.1.5 on 2020-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0127_auto_20200908_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdate',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
