# Generated by Django 2.1.5 on 2020-09-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0129_auto_20200916_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupdate',
            name='is_available',
            field=models.CharField(default='checked', max_length=80, null=True),
        ),
    ]
